webapp/routes/dashboard.py
from flask import Blueprint, render_template, current_app, flash
from flask_login import login_required, current_user
from webapp.utils.decorators import role_required
from webapp.models.models_file import Course, Enrollment
from webapp import db

dashboard_bp = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@dashboard_bp.route('/student', methods=['GET'])
@login_required
@role_required('student')
def student_dashboard():
    """
    Displays a student's dashboard showing their enrolled courses
    and other available courses they can join
    """
    try:
        print("Started to run....")
        # All enrolled courses
        enrolled_courses = (
            Course.query
            .join(Enrollment, Enrollment.course_id == Course.id)
            .filter(Enrollment.user_id == current_user.id)
            .all()
        )

        print(enrolled_courses)

        enrolled_ids = {course.id for course in enrolled_courses}

        # Get not enrolled courses
        courses_to_show = Course.query.filter(~Course.id.in_(enrolled_ids)).all()

        return render_template(
            'dashboard/student.html',
            enrolled_courses=enrolled_courses,
            courses=courses_to_show
        )

    except Exception as e:
        current_app.logger.error(f"Error loading dashboard for user {current_user.id}: {e}")
        flash('Unable to load your dashboard at the moment.', 'error')
        return render_template(
            'dashboard/student.html',
            enrolled_courses=[],
            courses=[]
        )


@dashboard_bp.route('/professor')
@login_required
@role_required('professor')
def professor_dashboard():
    """
    Handles professor view on the dashboard
        1. Allows view to all students enrolled in user's courses
        2. 
    Return: enrollments page
    """
    user_id = current_user.id
    courses = Course.query.filter_by(professor_id=user_id).all()
    enrollments = Enrollment.query.filter(Enrollment.course_id.in_([c.id for c in courses])).all()

    return render_template('dashboard/professor.html', enrollments=enrollments)

webapp/routes/grades.py
from flask import Blueprint, redirect, url_for, request, flash, current_app, render_template
from webapp.utils.decorators import role_required
from webapp.utils.helpers import clean_form_data, get_letter_grade
from webapp import db
from webapp.models.models_file import Enrollment
from flask_login import login_required, current_user
from datetime import datetime, timezone

grades_bp = Blueprint('grades', __name__, url_prefix='/grades')


@grades_bp.route('/add', methods=['POST'])
@login_required
@role_required('professor')
def grade_student():
    form_data = request.form
    cleaned_data = clean_form_data(form_data)
    
    cleaned_score = cleaned_data.get('score')
    student_id = cleaned_data.get('student_id')
    course_id = cleaned_data.get('course_id')

    score = 0
    letter_grade = ''

    if cleaned_score:
        score = float(cleaned_score)
        letter_grade = get_letter_grade(score)

    enrollment = db.session.query(Enrollment).filter(
        Enrollment.user_id == student_id,
        Enrollment.course_id == course_id
    ).first()

    # enrollment does not exist
    if not enrollment:
        flash('Enrollment does not exist or student already graded', 'error')
        return redirect(url_for('dashboard.professor_dashboard'))
    
    # If the student has not been graded yet - score is None
    try:
        if enrollment.score is None:
            enrollment.score = score
            enrollment.letter_grade = letter_grade if cleaned_score else None
            enrollment.date_enrolled = datetime.now(timezone.utc)
            try:
                db.session.commit()
                flash('Grade added successfully', 'success')
            except Exception as e:
                db.session.rollback()
                current_app.logger.error(f'An error occurred: {e}')
        else:
            flash('Student is already graded', 'warning')

    except Exception as e:
        db.session.rollback()
        current_app.logger.error(f'An error occured: {e}')

    return redirect(url_for('dashboard.professor_dashboard'))

@grades_bp.route('/view', methods=['GET'])
@login_required
@role_required('student')
def view_grades():
    enrollments = db.session.query(Enrollment).filter_by(user_id=current_user.id).all()
    enrollments_list = list(enrollments) if enrollments else []
    if not enrollments_list:
        flash('No enrollments were found for this user', 'error')
        current_app.logger.error(f'No enrollments were found for this user. UserId: {current_user.id}')
        return render_template('enrollments/enrollment.html', enrollments=[])
    return render_template('enrollments/enrollment.html', enrollments=enrollments_list)

webapp/templates/dashboard/professor.html
{% extends 'base.html' %} {% block title %}Professor Dashboard{% endblock %} {%
block extra_css %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/dashboard/professor_dash.css') }}"
/>
{% endblock %} {% block content %}
<div class="dashboard-section">
  <h1>Welcome, Professor {{ current_user.name }}!</h1>
  <p>Manage your courses and student enrollments efficiently.</p>
</div>

<section>
  <h2>Enrollments in Your Courses</h2>

  {% if enrollments %}
  <div class="enrollment-table-container">
    <table class="enrollment-table">
      <thead>
        <tr>
          <th>Student</th>
          <th>Course</th>
          <th>Score</th>
          <th>Letter Grade</th>
          <th>Date Enrolled</th>
        </tr>
      </thead>
      <tbody>
        {% for enrollment in enrollments %}
        <tr>
          <td>{{ enrollment.student.name }}</td>
          <td>{{ enrollment.course.name }}</td>
          <td>{{ enrollment.score or 'N/A' }}</td>
          <td>{{ enrollment.letter_grade or 'N/A' }}</td>
          <td>
            {{ enrollment.date_enrolled.strftime('%Y-%m-%d') if
            enrollment.date_enrolled else 'N/A' }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="grades">
    {% set ungraded = enrollments|selectattr('score','equalto',None)|list %} {%
    if ungraded %} {% for enrollment in ungraded %}
    <h2>Ungraded students</h2>
    <ol>
      <li>
        {{ enrollment.student.name }} has not been graded yet for {{
        enrollment.course.name }}.
      </li>
    </ol>
    <button
      class="grade-btn"
      data-student-id="{{ enrollment.student.id }}"
      data-course-id="{{ enrollment.course.id }}"
      data-course-name="{{ enrollment.course.name }}"
      data-student-name="{{ enrollment.student.name }}"
    >
      Grade Student
    </button>
    {% endfor %} {% else %}
    <div>All students are already graded.</div>
    {% endif %}
  </div>

  <!-- Grade student modal -->
  <dialog id="modal" class="modal">
    <div class="modal-content">
      <h2 id="modal-title"></h2>
      <form
        action="{{ url_for('grades.grade_student') }}"
        method="post"
        class="active"
      >
        <label for="course">
          Course
          <input type="text" name="course" id="course" readonly />
        </label>
        <label for="score">
          Enter the score
          <input
            type="number"
            name="score"
            id="score"
            required
            min="1"
            max="100"
          />
        </label>
        <input type="hidden" name="student_id" id="student-id" />
        <input type="hidden" name="course_id" id="course-id" />
        <div class="button-row">
          <button class="action-btn delete" type="button" id="close-modal">
            Cancel
          </button>
          <button class="action-btn view" id="send-data">Submit</button>
        </div>
      </form>
    </div>
  </dialog>
  {% else %}
  <p style="text-align: center; margin-top: 1rem">No enrollments found.</p>
  {% endif %}
</section>
{% endblock %} {% block extra_js %}
<script src="{{ url_for('static', filename='js/dashboard/professor_dash.js') }}"></script>
{% endblock %}

webapp/templates/dashboard/student.html
{% extends "base.html" %} {% block title %}Student Dashboard{% endblock %} {%
block extra_css %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/dashboard/student_dash.css') }}"
/>
{% endblock %} {% block content %}
<div class="dashboard-container">
  <!-- Header -->
  <header class="dashboard-header">
    <h1>Welcome, {{ current_user.name }}!</h1>
    <p>Here’s what you’re enrolled in — and what’s waiting for you.</p>
  </header>

  <!-- Enrolled Courses -->
  <section class="courses-section">
    <h2 class="section-title">Your Enrolled Courses</h2>

    {% if enrolled_courses %}
    <div class="course-grid">
      {% for course in enrolled_courses %}
      <div class="course-card enrolled">
        <div class="course-content">
          <h3 class="course-title">{{ course.name }}</h3>
          <!--TODO: Add description-->
          <a
            href="{{ url_for('course.view_course', course_id=course.id) }}"
            class="btn primary"
            >Go to Course</a
          >
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="empty-state">You’re not enrolled in any courses yet.</div>
    {% endif %}
  </section>

  <hr class="divider" />

  <!-- Available Courses -->
  <section class="courses-section">
    <h2 class="section-title">Explore More Courses</h2>

    {% if courses %}
    <div class="course-grid">
      {% for course in courses %}
      <div class="course-card">
        <div class="course-content">
          <h3 class="course-title">{{ course.name }}</h3>
          <!--TODO: Add Description-->
          <button class="btn success" data-course-id="{{ course.id }}">
            Join Course
          </button>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="empty-state">No new courses available right now.</div>
    {% endif %}
  </section>
  <dialog id="modal" class="modal">
    <div class="modal-content">
      <h2>This will enroll you to this course</h2>

      <div class="button-row">
        <button class="action-btn delete close-modal">Cancel</button>
        <button class="action-btn view enroll-btn close-modal join-btn">
          Continue and enroll
        </button>
      </div>
    </div>
  </dialog>
</div>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const modal = document.getElementById("modal");
    const courseButtons = document.querySelectorAll("[data-course-id]");
    const modalButtons = document.querySelectorAll(".close-modal");

    let selectedCourseId = null;

    courseButtons.forEach((button) =>
      button.addEventListener("click", () => {
        selectedCourseId = button.dataset.courseId;
        modal.showModal();
      })
    );

    document.querySelector(".join-btn").addEventListener("click", () => {
      if (selectedCourseId) {
        joinCourse(selectedCourseId);
      }
    });

    modalButtons.forEach((btn) => btn.addEventListener("click", closeModal));

    function closeModal() {
      selectedCourseId = null;
      modal.close();
    }

    async function joinCourse(courseId) {
      try {
        const response = await fetch(`/enrollment/new`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            course_id: courseId,
          }),
        });

        if (response.ok) {
          location.reload();
        } else {
          console.log("Failed to join the course.");
        }
      } catch (err) {
        console.log(`An error occured: ${err}`);
      }
    }
  });
</script>
{% endblock %}